import { test, expect } from '@playwright/test';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { readFileSync, existsSync, rmSync } from 'node:fs';
import { launchApp, repoRoot, type LaunchedApp } from './helpers/launchApp';
import { importFiles } from './helpers/importFiles';
import { completeImportWizard } from './helpers/importWizard';
import { stubSaveDialog, getSaveDialogCalls } from './helpers/stubSaveDialog';

const FIXTURE = join(repoRoot, 'tests', 'e2e', 'fixtures', 'forest-plot.xyz');

// forest-plot.xyz: three synthetic stems of KNOWN size on a plane sloping
// 0.15 in x and -0.08 in y (see the file header, generated by
// backend-api/tests/synthetic_trees.py):
//
//   base (0, 0)    DBH 36 cm  height 12 m  vertical
//   base (7, 1)    DBH 24 cm  height 10 m  leaning 6 deg toward +x
//   base (2, 7.5)  DBH 30 cm  height 11 m  vertical
//
// The full workflow against the live backend, through the real UI:
// import -> Segment Ground -> Generate DEM (with height above ground) ->
// Segment Trees -> Tree Inventory. Asserts the measured DBH / height / lean in
// the table and in the exported CSVs, that the user's species entry reaches
// the CSV, that sorting reorders the table, and that clicking a row frames a
// (Segment Trees runs seeded by Auto-seed stems, and tiled.)
// different tree. Then the Stand tab (per-hectare figures, QMD, Lorey's
// height, histograms, Jenkins biomass, a dead tree leaving the stand) and the
// QSM tab (one QSM per tree into the scene, metrics CSV, volume in the table).
//
// One test, so one app: the four stages are one workflow, each depending on
// the previous one's columns.
const TRUTH = [
  { dbhCm: 36, heightM: 12, leanDeg: 0 },
  { dbhCm: 24, heightM: 10, leanDeg: 6 },
  { dbhCm: 30, heightM: 11, leanDeg: 0 },
];

let session: LaunchedApp;
test.beforeAll(async () => {
  session = await launchApp();
});
test.afterAll(async () => {
  await session?.close();
});

function cellNumber(text: string | null): number {
  return parseFloat((text ?? '').replace(/[^0-9.\-]/g, ''));
}

test('ground -> DEM -> trees -> inventory -> stand -> QSMs on known stems', async () => {
  test.setTimeout(8 * 60_000);
  const { app, page } = session;
  const treesCsv = join(tmpdir(), `phytograph_trees_e2e_${Date.now()}.csv`);
  const curveCsv = join(tmpdir(), `phytograph_stemcurve_e2e_${Date.now()}.csv`);
  for (const p of [treesCsv, curveCsv]) if (existsSync(p)) rmSync(p);

  try {
    await importFiles(app, page, 'import-point-cloud', FIXTURE);
    await completeImportWizard(page);
    const cloudRow = page.locator('[data-testid="scan-row"][data-scan-name="forest-plot"]');
    await expect(cloudRow).toBeVisible({ timeout: 30_000 });
    await expect(cloudRow).toHaveAttribute('data-selected', 'true');

    // 1) Ground.
    await page.getByTestId('tool-ground-segment').click();
    await expect(page.getByTestId('ground-segment-panel')).toBeVisible();
    await page.getByTestId('ground-segment-run-button').click();
    await expect(page.getByTestId('class-legend')).toBeVisible({ timeout: 120_000 });

    // 2) DEM with the height-above-ground column (the inventory's ground).
    await page.getByTestId('tool-dem').click();
    await expect(page.getByTestId('dem-panel')).toBeVisible();
    await page.getByTestId('dem-cell-size').fill('0.5');
    await page.getByTestId('dem-compute-hag').check();
    await page.getByTestId('dem-run-button').click();
    await expect(page.locator('[data-testid="mesh-row"][data-mesh-name="forest-plot DEM"]'))
      .toBeVisible({ timeout: 120_000 });
    await expect(page.getByTestId('scalar-overlay'))
      .toHaveAttribute('data-active-scalar', 'height_above_ground', { timeout: 60_000 });

    // 3) Trees.
    // The DEM mesh may have taken the selection; a click on a selected row
    // would toggle it off, so only click when it is not selected.
    if ((await cloudRow.getAttribute('data-selected')) !== 'true') {
      await cloudRow.click({ position: { x: 40, y: 8 } });
    }
    await expect(cloudRow).toHaveAttribute('data-selected', 'true');
    await page.getByTestId('tool-tree-segment').click();
    await expect(page.getByTestId('tree-segment-panel')).toBeVisible();
    // Automatic stem seeds: one per trunk, found in the 1-2 m layer above
    // the DEM - exactly the three stems of the fixture.
    await page.getByTestId('tree-auto-seed').click();
    await expect(page.getByTestId('tree-seed-count')).toHaveText('3 seeds', { timeout: 60_000 });
    // Tiled segmentation, seeded: every tree kept from the tile its seed is in.
    await page.getByTestId('tree-tiling').selectOption('on');
    await page.getByTestId('tree-segment-run-button').click();
    await expect(page.getByTestId('scalar-overlay'))
      .toHaveAttribute('data-active-scalar', 'tree_instance', { timeout: 180_000 });

    // 4) Inventory. The panel names the ground source it will use.
    await page.getByTestId('tool-tree-inventory').click();
    const panel = page.getByTestId('tree-inventory-panel');
    await expect(panel).toBeVisible();
    await expect(page.getByTestId('tree-inventory-ground-source'))
      .toHaveAttribute('data-ground-source', 'height_above_ground');
    // Every setting explains itself on hover: the two that are not
    // self-explanatory say what they change.
    await page.getByTestId('tree-inventory-competition-help').hover();
    await expect(page.getByRole('tooltip')).toContainText('competition index (the CI column');
    await page.getByTestId('tree-inventory-voxel-help').hover();
    await expect(page.getByRole('tooltip')).toContainText('Only affects the crown volume column');
    for (const key of ['breast-height', 'fit-method', 'min-points']) {
      await expect(page.getByTestId(`tree-inventory-${key}-help`)).toBeVisible();
    }
    await page.mouse.move(0, 0);
    await expect(page.getByTestId('tree-inventory-run')).toBeEnabled();
    await page.getByTestId('tree-inventory-run').click();
    const summary = page.getByTestId('tree-inventory-summary');
    await expect(summary).toBeVisible({ timeout: 180_000 });

    // Every known stem appears as a row with its DBH, height and lean.
    const rows = page.getByTestId('tree-row');
    const n = await rows.count();
    expect(n).toBeGreaterThanOrEqual(3);
    const measured: { id: number; dbhCm: number; heightM: number; leanDeg: number }[] = [];
    for (let i = 0; i < n; i++) {
      const r = rows.nth(i);
      measured.push({
        id: parseInt((await r.getAttribute('data-tree-id')) ?? '0', 10),
        dbhCm: cellNumber(await r.locator('[data-col="dbh_cm"]').textContent()),
        heightM: cellNumber(await r.locator('[data-col="height_m"]').textContent()),
        leanDeg: cellNumber(await r.locator('[data-col="lean_deg"]').textContent()),
      });
    }
    const matched = TRUTH.map(truth => {
      const m = measured.find(x => Math.abs(x.dbhCm - truth.dbhCm) <= 1.5);
      expect(m, `no row with DBH ~${truth.dbhCm} cm; rows: ${JSON.stringify(measured)}`).toBeTruthy();
      expect(m!.heightM).toBeGreaterThan(truth.heightM - 0.4);
      expect(m!.heightM).toBeLessThan(truth.heightM + 0.4);
      expect(Math.abs(m!.leanDeg - truth.leanDeg)).toBeLessThan(1.5);
      return m!;
    });
    expect(new Set(matched.map(m => m.id)).size).toBe(3);

    // Sorting by DBH (first click = descending) puts the 36 cm stem first.
    await page.getByTestId('tree-table-sort-dbh_cm').click();
    await expect(page.getByTestId('tree-table-sort-dbh_cm')).toHaveAttribute('data-sort', 'desc');
    expect(cellNumber(await rows.first().locator('[data-col="dbh_cm"]').textContent()))
      .toBeGreaterThan(34.5);

    // Clicking a row selects it and frames that tree: two trees 7 m apart
    // give camera targets several metres apart.
    const target = async () => (await page.evaluate(() => (window as any).__getCameraState().target)) as number[];
    const rowOf = (id: number) => page.locator(`[data-testid="tree-row"][data-tree-id="${id}"]`);
    await rowOf(matched[0].id).click();
    await expect(rowOf(matched[0].id)).toHaveAttribute('data-selected', 'true');
    const t0 = await target();
    await rowOf(matched[1].id).click();
    await expect(rowOf(matched[1].id)).toHaveAttribute('data-selected', 'true');
    const t1 = await target();
    expect(Math.hypot(t1[0] - t0[0], t1[1] - t0[1])).toBeGreaterThan(5);

    // A species entry travels into the tree-list CSV.
    await rowOf(matched[2].id).getByTestId('tree-species').fill('Quercus robur');
    await rowOf(matched[2].id).getByTestId('tree-status').selectOption('live');

    await stubSaveDialog(app, treesCsv);
    await page.getByTestId('tree-inventory-export-trees').click();
    await expect.poll(async () => (await getSaveDialogCalls(app)).length, { timeout: 15_000 }).toBeGreaterThan(0);
    let csv = '';
    await expect.poll(() => {
      csv = existsSync(treesCsv) ? readFileSync(treesCsv, 'utf-8') : '';
      return csv.trim().split('\n').length;
    }, { timeout: 15_000 }).toBe(n + 1);
    const lines = csv.trim().split('\n').map(l => l.split(','));
    const header = lines[0];
    const col = (name: string) => header.indexOf(name);
    for (const m of matched) {
      const row = lines.find(l => l[col('tree_id')] === String(m.id))!;
      expect(parseFloat(row[col('dbh_m')]) * 100).toBeCloseTo(m.dbhCm, 0);
      expect(row[col('ground_source')]).toBe('height_above_ground');
    }
    const oak = lines.find(l => l[col('tree_id')] === String(matched[2].id))!;
    expect(oak[col('species')]).toBe('Quercus robur');
    expect(oak[col('status')]).toBe('live');
    // The 36 cm stem stands at the plot origin: its stem base is there.
    const big = lines.find(l => l[col('tree_id')] === String(matched[0].id))!;
    expect(Math.abs(parseFloat(big[col('stem_x')]))).toBeLessThan(0.05);
    expect(Math.abs(parseFloat(big[col('stem_y')]))).toBeLessThan(0.05);
    expect(parseFloat(big[col('ground_z')])).toBeCloseTo(100, 1);

    // Stem curve: several ok slices per measured tree, diameters near its DBH low down.
    await stubSaveDialog(app, curveCsv);
    await page.getByTestId('tree-inventory-export-stem-curve').click();
    let curve = '';
    await expect.poll(() => {
      curve = existsSync(curveCsv) ? readFileSync(curveCsv, 'utf-8') : '';
      return curve.startsWith('scan_name,tree_id,axial_m');
    }, { timeout: 15_000 }).toBe(true);
    const cRows = curve.trim().split('\n').slice(1).map(l => l.split(','));
    for (const m of matched) {
      const mine = cRows.filter(r => r[1] === String(m.id) && r[11] === 'true');
      expect(mine.length).toBeGreaterThanOrEqual(5);
      const low = mine.find(r => parseFloat(r[2]) === 1.5)!;
      expect(parseFloat(low[7]) * 100).toBeGreaterThan(m.dbhCm - 2);
      expect(parseFloat(low[7]) * 100).toBeLessThan(m.dbhCm + 1);
    }

    // ---- Stand tab ----
    // Per-hectare figures from the DBHs in the table and an entered area.
    await page.getByTestId('tree-inventory-tab-stand').click();
    await expect(page.getByTestId('stand-summary')).toBeVisible();
    // The measured plot boundary is the ground points' hull: about 15 x 15.5 m.
    await expect(page.getByTestId('stand-plot-area-value')).toHaveAttribute('data-source', 'measured');
    const measuredArea = cellNumber(await page.getByTestId('stand-plot-area-value').textContent());
    expect(measuredArea).toBeGreaterThan(200);
    expect(measuredArea).toBeLessThan(260);
    await page.getByTestId('stand-plot-area').fill('400');
    await page.getByTestId('stand-plot-area').press('Enter');
    await expect(page.getByTestId('stand-plot-area-value')).toHaveAttribute('data-source', 'entered');
    await expect(page.getByTestId('stand-n-trees')).toHaveText('3');
    await expect(page.getByTestId('stand-stems-ha')).toHaveText('75');   // 3 / 400 m² · 10⁴
    const d = matched.map(m => m.dbhCm / 100);
    const baHa = d.reduce((a, x) => a + Math.PI / 4 * x * x, 0) / 400 * 1e4;
    expect(cellNumber(await page.getByTestId('stand-ba-ha').textContent())).toBeCloseTo(baHa, 1);
    const qmd = Math.sqrt(d.reduce((a, x) => a + x * x, 0) / 3) * 100;
    expect(Math.abs(cellNumber(await page.getByTestId('stand-qmd').textContent()) - qmd)).toBeLessThan(0.2);
    // Lorey's height lies between the lowest and tallest tree, nearer the big one.
    const lorey = cellNumber(await page.getByTestId('stand-lorey').textContent());
    expect(lorey).toBeGreaterThan(10.5);
    expect(lorey).toBeLessThan(12.1);
    // The three DBHs land in three 5 cm classes.
    const bins = page.getByTestId('stand-dbh-hist-bin');
    const counts = await bins.evaluateAll(els => els.map(e => Number(e.getAttribute('data-count'))));
    expect(counts.reduce((a, b) => a + b, 0)).toBe(3);

    // Biomass by Jenkins et al. (2003), pine group: exp(-2.5356 + 2.4349 ln D).
    await page.getByTestId('stand-biomass-method').selectOption('jenkins2003');
    await page.getByTestId('stand-jenkins-group').selectOption('pine');
    const agb = matched.reduce((a, m) => a + Math.exp(-2.5356 + 2.4349 * Math.log(m.dbhCm)), 0);
    const shownMg = cellNumber(await page.getByTestId('stand-biomass').textContent());
    expect(Math.abs(shownMg - agb / 1000)).toBeLessThan(0.05);

    // A tree marked dead leaves the stand.
    await page.getByTestId('tree-inventory-tab-trees').click();
    await rowOf(matched[1].id).getByTestId('tree-status').selectOption('dead');
    await page.getByTestId('tree-inventory-tab-stand').click();
    await expect(page.getByTestId('stand-n-trees')).toHaveText('2');
    await expect(page.getByTestId('stand-stems-ha')).toHaveText('50');

    // ---- QSM tab ----
    // One QSM per tree, added to the scene; its metrics CSV has one row per tree.
    await page.getByTestId('tree-inventory-tab-qsm').click();
    await page.getByTestId('tree-qsm-build').click();
    const qsmSummary = page.getByTestId('tree-qsm-summary');
    await expect(qsmSummary).toBeVisible({ timeout: 300_000 });
    const built = parseInt((await qsmSummary.getAttribute('data-built')) ?? '0', 10);
    const failed = parseInt((await qsmSummary.getAttribute('data-failed')) ?? '0', 10);
    expect(built + failed).toBe(n);
    expect(built).toBeGreaterThanOrEqual(3);
    await expect(page.getByTestId('qsm-row')).toHaveCount(built);
    const qsmCsvPath = join(tmpdir(), `phytograph_treeqsm_e2e_${Date.now()}.csv`);
    try {
      await stubSaveDialog(app, qsmCsvPath);
      await page.getByTestId('tree-qsm-export').click();
      let qsmCsv = '';
      await expect.poll(() => {
        qsmCsv = existsSync(qsmCsvPath) ? readFileSync(qsmCsvPath, 'utf-8') : '';
        return qsmCsv.trim().split('\n').length;
      }, { timeout: 15_000 }).toBe(n + 1);
      const qh = qsmCsv.split('\n')[0].split(',');
      for (const m of matched) {
        const r = qsmCsv.split('\n').find(l => l.split(',')[qh.indexOf('tree_id')] === String(m.id))!.split(',');
        expect(r[qh.indexOf('success')]).toBe('true');
        expect(parseFloat(r[qh.indexOf('total_woody_volume_m3')])).toBeGreaterThan(0);
      }
    } finally {
      if (existsSync(qsmCsvPath)) rmSync(qsmCsvPath);
    }
    // The woody volume joins the tree table.
    await page.getByTestId('tree-inventory-tab-trees').click();
    expect(cellNumber(await rowOf(matched[0].id).locator('[data-col="qsm_volume_m3"]').textContent()))
      .toBeGreaterThan(0);
  } finally {
    for (const p of [treesCsv, curveCsv]) if (existsSync(p)) rmSync(p);
  }
});
