"""Generate the committed MOVING-platform LAD leaf-cube fixture.

Run once to (re)produce `lad-leafcube-moving/`:
  - leafcube_moving.xyz  — x y z timestamp is_miss  (the moving scan's returns)
  - leafcube_moving.xml  — scan wrapper for Add Scan -> Import from XML
  - trajectory.csv       — t x y z qx qy qz qw  (the platform path)

The scan is a moving-platform sweep over the PyHelios `lidar` plugin's
`leaf_cube_LAI2_lw0_01_spherical.xml` geometry (LAI=2, spherical leaf angles →
analytic G(theta)=0.5, true LAD=2.0 m^2/m^3 for the single 1x1x1 voxel). The
platform translates ~2 m along +x at altitude z=5 with identity attitude while
the head sweeps, so each return has its OWN per-pulse origin — exactly what the
beam-based (Gtheta) inversion consumes. addScanMoving writes a real per-pulse
timestamp; we persist it so the importer can join the trajectory back.

Usage (from repo root, backend venv active, libhelios built):
    cd pyhelios/helios-core
    python ../../backend-api/tests/fixtures/generate_lad_leafcube_moving.py
"""

import math
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_PYHELIOS = os.path.abspath(os.path.join(_HERE, "..", "..", "..", "pyhelios"))
sys.path.insert(0, _PYHELIOS)

from pyhelios import LiDARCloud, Context  # noqa: E402

GEOM = "plugins/lidar/xml/leaf_cube_LAI2_lw0_01_spherical.xml"

# Straight pass above the cube; identity attitude. Kept coarse so the committed
# cloud stays small while the moving geometry is still exercised end to end.
NTHETA, NPHI = 400, 650
P0 = [-1.0, 0.0, 5.0]
P1 = [1.0, 0.0, 5.0]
GRID_CENTER = [0.0, 0.0, 0.5]
GRID_SIZE = [1.0, 1.0, 1.0]

OUT_DIR = os.environ.get(
    "LAD_LEAFCUBE_MOVING_OUT", os.path.join(_HERE, "lad-leafcube-moving"))


def main():
    if not os.path.isfile(GEOM):
        raise SystemExit(
            f"Geometry not found at '{GEOM}'. Run this script from "
            "pyhelios/helios-core so the relative path resolves.")

    os.makedirs(OUT_DIR, exist_ok=True)

    cloud = LiDARCloud()
    cloud.disableMessages()
    cloud.addScanMoving(
        Ntheta=NTHETA, theta_range=(0.0, math.pi),
        Nphi=NPHI, phi_range=(0.0, 2 * math.pi),
        exit_diameter=0.0, beam_divergence=0.0,
        traj_t=[0.0, 1.0],
        traj_pos=[P0, P1],
        traj_rot=[[0, 0, 0, 1], [0, 0, 0, 1]],
        pulse_rate_hz=float(NTHETA * NPHI),  # whole sweep over ~1 s
        rot_is_quaternion=True)

    with Context() as ctx:
        ctx.loadXML(GEOM, True)
        cloud.syntheticScan(ctx, record_misses=True)
        n = cloud.getHitCount()
        positions, _ = cloud.getHitsXYZRGB()
        timestamp = cloud.getHitDataAll("timestamp")
        is_miss = cloud.getHitDataAll("is_miss")

    xyz_path = os.path.join(OUT_DIR, "leafcube_moving.xyz")
    with open(xyz_path, "w") as f:
        for p, t, m in zip(positions, timestamp, is_miss):
            f.write(f"{p.x:.4f} {p.y:.4f} {p.z:.4f} {t:.6f} {1.0 if m else 0.0:.1f}\n")

    traj_path = os.path.join(OUT_DIR, "trajectory.csv")
    with open(traj_path, "w") as f:
        f.write("# t x y z qx qy qz qw\n")
        f.write(f"0.0 {P0[0]} {P0[1]} {P0[2]} 0 0 0 1\n")
        f.write(f"1.0 {P1[0]} {P1[1]} {P1[2]} 0 0 0 1\n")

    xml_path = os.path.join(OUT_DIR, "leafcube_moving.xml")
    with open(xml_path, "w") as f:
        f.write(
            '<?xml version="1.0"?>\n\n'
            '<!--\n'
            '  Moving-platform synthetic scan of the lidar plugin\'s\n'
            '  leaf_cube_LAI2_lw0_01_spherical geometry (LAI=2, spherical leaf\n'
            '  angles). The platform translates ~2 m along +x at z=5 over the\n'
            '  sweep. Per-voxel true LAD=2.0 m^2/m^3, G(theta)=0.5. Import the\n'
            '  scan via Add Scan -> Import from XML, then attach trajectory.csv\n'
            '  via "Import trajectory file..." to make it a moving-platform scan.\n'
            f'  Generated by generate_lad_leafcube_moving.py ({NTHETA}x{NPHI}).\n'
            '-->\n\n'
            '<helios>\n\n'
            '<scan>\n'
            '  <filename> leafcube_moving.xyz </filename>\n'
            '  <ASCII_format> x y z timestamp is_miss </ASCII_format>\n'
            f'  <origin> {P0[0]:.6f} {P0[1]:.6f} {P0[2]:.6f} </origin>\n'
            f'  <size> {NTHETA} {NPHI} </size>\n'
            '</scan>\n\n'
            '</helios>\n')

    size_kb = os.path.getsize(xyz_path) / 1024
    print(f"Wrote {n} points to {xyz_path} ({size_kb:.1f} KB)")
    print(f"Wrote trajectory {traj_path}")
    print(f"Wrote scan wrapper {xml_path}")


if __name__ == "__main__":
    main()
