"""Generate the committed LAD leaf-cube point-cloud fixture.

Run once to (re)produce `lad-leafcube/leafcube.xyz` + `leafcube.xml`. The fixture
is a single discrete-return synthetic scan of the PyHelios `lidar` plugin's
`leaf_cube_LAI2_lw0_01_spherical.xml` geometry (a 1x1x1 m cube of leaves with
LAI=2 and a spherical leaf-angle distribution → analytic G(theta)=0.5, true
LAD=2.0 m^2/m^3 for the single 1x1x1 voxel).

We use a reduced angular resolution (vs. the C++ self-test's 6000x12000) so the
committed point cloud stays small (~380 KB, ~18k points) while still recovering
LAD within ~10% — point-cloud triangulation is noisier than the C++ test's pure
synthetic G(theta), so the test tolerances are looser than the C++ 2%/5%.

Usage (from repo root, with the backend venv active and libhelios built):
    cd pyhelios/helios-core           # so the GEOM relative path resolves
    python ../../backend-api/tests/fixtures/generate_lad_leafcube.py
"""

import math
import os
import sys

# Resolve pyhelios from the source submodule.
_HERE = os.path.dirname(os.path.abspath(__file__))
_PYHELIOS = os.path.abspath(os.path.join(_HERE, "..", "..", "..", "pyhelios"))
sys.path.insert(0, _PYHELIOS)

from pyhelios import LiDARCloud, Context  # noqa: E402

# Geometry path is relative to pyhelios/helios-core (Helios resolves project
# files from the working directory). Run this script from there.
GEOM = "plugins/lidar/xml/leaf_cube_LAI2_lw0_01_spherical.xml"

ORIGIN = (-5.0, 0.0, 0.5)
NTHETA, NPHI = 2600, 5200            # reduced from the C++ 6000x12000
GRID_CENTER = [0.0, 0.0, 0.5]
GRID_SIZE = [1.0, 1.0, 1.0]

# Override with LAD_LEAFCUBE_OUT to regenerate the E2E copy
# (tests/e2e/fixtures/lad-leafcube), which is the same scan.
OUT_DIR = os.environ.get("LAD_LEAFCUBE_OUT", os.path.join(_HERE, "lad-leafcube"))


def main():
    if not os.path.isfile(GEOM):
        raise SystemExit(
            f"Geometry not found at '{GEOM}'. Run this script from "
            "pyhelios/helios-core so the relative path resolves.")

    os.makedirs(OUT_DIR, exist_ok=True)

    cloud = LiDARCloud()
    cloud.disableMessages()
    cloud.addScan(
        origin=list(ORIGIN), Ntheta=NTHETA, theta_range=(0.0, math.pi),
        Nphi=NPHI, phi_range=(0.0, 2 * math.pi),
        exit_diameter=0.0, beam_divergence=0.0)
    cloud.addGrid(center=GRID_CENTER, size=GRID_SIZE, ndiv=[1, 1, 1])

    with Context() as ctx:
        ctx.loadXML(GEOM, True)
        # Record misses: calculateLeafArea() fail-fasts on a cloud with no miss
        # points (it needs the transmitted-beam population for the Beer's-law
        # denominator). Helios tags every hit with is_miss (0.0 return / 1.0 miss);
        # we persist it as a 4th column so the importer carries misses too.
        cloud.syntheticScan(ctx, record_misses=True)
        n = cloud.getHitCount()
        cloud.triangulateHitPoints(0.04, 10)
        cloud.calculateLeafArea(ctx)
        lad = cloud.getCellLeafAreaDensity(0)
        gtheta = cloud.getCellGtheta(0)
        positions, _ = cloud.getHitsXYZRGB()
        is_miss = cloud.getHitDataAll("is_miss")

    xyz_path = os.path.join(OUT_DIR, "leafcube.xyz")
    with open(xyz_path, "w") as f:
        for p, m in zip(positions, is_miss):
            f.write(f"{p.x:.4f} {p.y:.4f} {p.z:.4f} {1.0 if m else 0.0:.1f}\n")

    # XML wrapper so the Phytograph importer attaches the scan params
    # (origin + Ntheta/Nphi) when imported via Add Scan -> Import from XML.
    xml_path = os.path.join(OUT_DIR, "leafcube.xml")
    with open(xml_path, "w") as f:
        f.write(
            '<?xml version="1.0"?>\n\n'
            '<!--\n'
            '  Single discrete-return synthetic scan of the lidar plugin\'s\n'
            '  leaf_cube_LAI2_lw0_01_spherical geometry (LAI=2, spherical leaf\n'
            '  angles). Used to test per-voxel leaf area density: the 1x1x1 m\n'
            '  voxel at (0,0,0.5) has true LAD=2.0 m^2/m^3 and G(theta)=0.5.\n'
            f'  Generated by generate_lad_leafcube.py ({NTHETA}x{NPHI}).\n'
            '-->\n\n'
            '<helios>\n\n'
            '<scan>\n'
            '  <filename> leafcube.xyz </filename>\n'
            '  <ASCII_format> x y z is_miss </ASCII_format>\n'
            f'  <origin> {ORIGIN[0]:.6f} {ORIGIN[1]:.6f} {ORIGIN[2]:.6f} </origin>\n'
            f'  <size> {NTHETA} {NPHI} </size>\n'
            '</scan>\n\n'
            '</helios>\n')

    size_kb = os.path.getsize(xyz_path) / 1024
    print(f"Wrote {n} points to {xyz_path} ({size_kb:.1f} KB)")
    print(f"Recovered LAD={lad:.4f} m^2/m^3 (true 2.0), G(theta)={gtheta:.4f} (true 0.5)")
    print(f"Wrote scan wrapper {xml_path}")


if __name__ == "__main__":
    main()
