"""Generate the committed multi-return LAD leaf-cube fixture.

Run once to (re)produce `lad-leafcube-multi/leafcube_multi.xyz` + `.xml`. Unlike
the single-return fixture, this is a **full-waveform** synthetic scan
(`rays_per_pulse` > 1 with a finite beam) of the same LAI=2 spherical leaf cube,
so most pulses produce several returns. Each hit carries the per-pulse columns
`timestamp target_index target_count`, which is what makes Helios run the
multi-return LAD algorithm (isMultiReturnData() + gapfillMisses()).

The 1x1x1 m voxel at (0,0,0.5) has true LAD=2.0 m^2/m^3 and G(theta)=0.5;
point-cloud multi-return recovery lands within ~15%.

Usage (from repo root, with the backend venv active and libhelios built):
    cd pyhelios/helios-core
    python ../../backend-api/tests/fixtures/generate_lad_leafcube_multireturn.py
"""

import math
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_PYHELIOS = os.path.abspath(os.path.join(_HERE, "..", "..", "..", "pyhelios"))
sys.path.insert(0, _PYHELIOS)

from pyhelios import LiDARCloud, Context  # noqa: E402

GEOM = "plugins/lidar/xml/leaf_cube_LAI2_lw0_01_spherical.xml"

ORIGIN = (-5.0, 0.0, 0.5)
NTHETA, NPHI = 800, 1600
RAYS_PER_PULSE = 10
PULSE_DISTANCE_THRESHOLD = 0.02
EXIT_DIAMETER = 0.01       # m — a finite beam so a pulse can split across leaves
BEAM_DIVERGENCE = 0.0003   # rad
GRID_CENTER = [0.0, 0.0, 0.5]
GRID_SIZE = [1.0, 1.0, 1.0]
COLUMNS = ("timestamp", "target_index", "target_count")

OUT_DIR = os.path.join(_HERE, "lad-leafcube-multi")


def main():
    if not os.path.isfile(GEOM):
        raise SystemExit(
            f"Geometry not found at '{GEOM}'. Run from pyhelios/helios-core.")

    os.makedirs(OUT_DIR, exist_ok=True)

    cloud = LiDARCloud()
    cloud.disableMessages()
    cloud.addScan(
        origin=list(ORIGIN), Ntheta=NTHETA, theta_range=(0.0, math.pi),
        Nphi=NPHI, phi_range=(0.0, 2 * math.pi),
        exit_diameter=EXIT_DIAMETER, beam_divergence=BEAM_DIVERGENCE)
    cloud.addGrid(center=GRID_CENTER, size=GRID_SIZE, ndiv=[1, 1, 1])

    with Context() as ctx:
        ctx.loadXML(GEOM, True)
        # Full-waveform scan: multiple rays per pulse, record misses so the
        # transmission gaps are present for the multi-return inversion.
        cloud.syntheticScan(
            ctx, rays_per_pulse=RAYS_PER_PULSE,
            pulse_distance_threshold=PULSE_DISTANCE_THRESHOLD,
            record_misses=True)
        n = cloud.getHitCount()

        positions, _ = cloud.getHitsXYZRGB()
        cols = {c: cloud.getHitDataAll(c) for c in COLUMNS}
        n_multi = sum(1 for v in cols["target_count"] if v and v > 1)

        # Verify the pipeline recovers a sane LAD before committing.
        cloud.gapfillMisses()
        cloud.triangulateHitPoints(0.04, 10)
        cloud.calculateLeafArea(ctx)
        lad = cloud.getCellLeafAreaDensity(0)
        gtheta = cloud.getCellGtheta(0)

    xyz_path = os.path.join(OUT_DIR, "leafcube_multi.xyz")
    with open(xyz_path, "w") as f:
        for i, p in enumerate(positions):
            ts = cols["timestamp"][i]
            ti = cols["target_index"][i]
            tc = cols["target_count"][i]
            f.write(f"{p.x:.4f} {p.y:.4f} {p.z:.4f} {ts:.4f} {int(ti)} {int(tc)}\n")

    xml_path = os.path.join(OUT_DIR, "leafcube_multi.xml")
    with open(xml_path, "w") as f:
        f.write(
            '<?xml version="1.0"?>\n\n'
            '<!--\n'
            '  Full-waveform (multi-return) synthetic scan of the lidar plugin\'s\n'
            '  leaf_cube_LAI2_lw0_01_spherical geometry (LAI=2). Each hit carries\n'
            '  per-pulse timestamp/target_index/target_count, so the LAD path runs\n'
            '  the multi-return algorithm. The 1x1x1 m voxel at (0,0,0.5) has true\n'
            '  LAD=2.0 m^2/m^3 and G(theta)=0.5.\n'
            f'  Generated by generate_lad_leafcube_multireturn.py.\n'
            '-->\n\n'
            '<helios>\n\n'
            '<scan>\n'
            '  <filename> leafcube_multi.xyz </filename>\n'
            '  <ASCII_format> x y z timestamp target_index target_count </ASCII_format>\n'
            f'  <origin> {ORIGIN[0]:.6f} {ORIGIN[1]:.6f} {ORIGIN[2]:.6f} </origin>\n'
            f'  <size> {NTHETA} {NPHI} </size>\n'
            '</scan>\n\n'
            '</helios>\n')

    size_kb = os.path.getsize(xyz_path) / 1024
    print(f"Wrote {n} points ({n_multi} multi-return) to {xyz_path} ({size_kb:.1f} KB)")
    print(f"Recovered LAD={lad:.4f} (true 2.0), G(theta)={gtheta:.4f} (true 0.5)")
    print(f"Wrote scan wrapper {xml_path}")


if __name__ == "__main__":
    main()
